name = "backend"
compatibility_date = "2023-12-01"


r2_buckets  = [ { binding = "R2_UPLOAD", bucket_name = "your-Bucket-name", preview_bucket_name = "preview-your-bucket-name"} ]

[vars]
DATABASE_URL=""
JWT_SECRET = "secret"
OPENAI_API_KEY = ""
R2_SUBDOMAIN_URL = "https://your-r2-subdomain-url.r2.dev"
