import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Heart, Home, Plus, Search, User } from "lucide-react";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Figuringout.life",
  description: "Generated by create next app",
};

const NavigationList = [
  {
    key: "home",
    href: "/",
    component: Home,
  },
  {
    key: "search",
    href: "",
    component: Search,
  },
  {
    key: "plus",
    href: "",
    component: Plus,
  },
  {
    key: "heart",
    href: "",
    component: Heart,
    className: "fill-black"
  },
  {
    key: "user",
    href: "",
    component: User,
    className: "fill-black"
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex bg-secondary bg-opacity-5`}
      >
        <div className="h-screen p-4 flex flex-col justify-center gap-8 bg-transparent border-0 shadow-none">
          {NavigationList.map(({ key, href, className = "", component: Component }) => (
            <Link key={key} href={href} className="hover:opacity-50">
              <Component width={24} height={24} className={className} />
            </Link>
          ))}

        </div>
        <div className="flex-1">{children}</div>
        <div className="absolute top-5 font-light left-20 border-2 p-2 bg-rose-900 text-secondary py-2">
          App under redesign
        </div>
      </body>
    </html>
  );
}
