export const topics = [
	"Family",
	"Health",
	"Relationships",
	"Mental Health",
	"Productivity",
	"Mindfulness",
	"Business",
	"Marketing",
	"Leadership",
	"Artifical Intelligence",
	"Blockchain",
	"Data Science",
	"Programming",
	"Programming Languages",
	"Dev Ops",
	"Writing",
	"Art",
	"Gaming",
	"Economics",
	"Educaiton",
	"Equality",
	"Philosophy",
	"Relgion",
	"Spirituality",
	"Cities",
	"Nature",
	"Travel",
];