export const topics = [
  "Family",
  "Health",
  "Relationships",
  "Mental Health",
  "Productivity",
  "Mindfulness",
  "Business",
  "Marketing",
  "Leadership",
  "Artifical Intelligence",
  "Blockchain",
  "Data Science",
  "Programming",
  "Programming Languages",
  "Dev Ops",
  "Writing",
  "Art",
  "Gaming",
  "Economics",
  "Education",
  "Equality",
  "Philosophy",
  "Relgion",
  "Spirituality",
  "Cities",
  "Nature",
  "Travel",
  "Technology",
  "Travel",
  "Food",
  "Fashion",
  "Sports",
  "Fitness",
  "Politics",
  "Science",
  "Entertainment",
  "Books",
  "Movies",
  "Music",
  "Photography",
  "Environment",
  "Parenting",
  "Self-improvement",
  "History",
  "Culture",
  "Social issues",
  "Career advice",
  "Finance",
  "Nature",
  "Home improvement",
  "Pet care",
  "Cooking",
  "DIY",
  "Motivation",
  "Life hacks",
  "Humor",
  "Technology trends",
  "Startup",
  "Digital Marketing",
  "Design",
  "Photography techniques",
  "Travel experiences",
  "Healthy recipes",
  "Entrepreneurship",
  "Film reviews",
  "Music recommendations",
  "Environmental conservation",
  "Parenting tips",
  "History facts",
  "Personal finance",
  "Game reviews",
  "Fashion trends",
  "Fitness workouts",
  "Book recommendations",
];